### ISSUE TITLE
Feature: file sharing

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#36]

**Comment by writerly03** [comment]
- what is meant by file sharing?
- Earthstar has a share, which is like a DB
- can work on things offline
- Eathstar is centralized because there aren't that many nodes currently
- how it resolves states is by the amount of time that you've been connect to the system
- still need to do more digging into this
- To do: create an info diagram that shows the interactions between peers when sharing files in Earthstar
-

**Comment by tripledoublev** [comment]
[Here is one of the web prototypes](https://hyphacoop.github.io/restructuring-futures/web/03_sharing-images/) where image files can be selected from the disk and added to the Replica.
It also supports _drag & drop_.  
I did tests with many images and eventually reached the dB's limit capacity.
I need to investigate instantiation of the Replica with [a different driver](https://earthstar-project.org/docs/developer-guide#persisting-data-with-drivers).

**Comment by tripledoublev** [comment]
The [image sharing prototype](https://hyphacoop.github.io/restructuring-futures/web/03_sharing-images/) validates the use-case for image files.

It would be useful to have a definite list of file types that should be supported.

There might be two ways to deal with support for various file type.
- Displaying file previews in app (in-browser image preview as shown with the image-sharing prototype)
- Providing a download link for files that can't be preview but can be retrieved (downloading a pdf to disk)


Based on the types of file allowed, incompatible types should be blocked.
For example, I just uploaded a pdf from the image-upload page. The pdf was successfully uploaded to the Share but it shows as a broken image since its rendering the files uploaded as images.

I would propose a type detection that blocks unsupported files.
The user would be warned that the selected file is not one that is supported by the app.
This file detection mechanism would then be use to properly handle de rendering of the file on retrieval.

**Comment by writerly03** [comment]
@luluissaa @jerroldmcgrath can you please add the types of file formats you want to be able to share? We're assuming:

- .jpg
- .png
- .gif
- .pdf
- .doc
- .csv
- .md

But is there anything else?

**Comment by writerly03** [comment]
Sprint 2 questions + success criteria

To do: 
1. be able to interact with file types other than images
2. add a download button 
3. add a delete button

connect to time stamping features

**Comment by jerroldmcgrath** [comment]
> 

.txt?

**Comment by writerly03** [comment]
Sprint 2 outcomes

- - file types that are now accepted: .jpg, .png, .txt., .md, .mp3, .ogg, .wave (some browsers)
- - not working: pdf (accepted as upload but not rendered on the page). File type can not be previewed but it can be shared 
- - when you upload a file a time stamp is added

**Comment by writerly03** [comment]
@tripledoublev A few things I've noticed in my interactions with the prototype:

- The map isn't mapping; i.e. when I select a square to drop the artefact, it always defaults to the upper left-hand corner
- when I return to the  prototype after a day, none of my previous artefacts are visible
- I can't seem to see other people's artefacts
- the artfact>attachment>get attachment flow seems cumbersome if the intent is to just view the thing (can it be fewer steps)
- how will his placing of object facilitate collaboration?
- will the chat always be attached to specific objects? this seems to facilitate collaboration, but am unsure because everything is gone when return to it

**Comment by tripledoublev** [comment]
@writerly03 thanks for the feedback!

 I've addressed some of your comments with small changes in the app.:

 - extended the lifespan of artifacts to 4 weeks
 - updated the layout so it maps more closely to the grid
 - i removed the _get attachment_ button to remove a step in the interactions necessary to get to see the attachment
