### ISSUE TITLE
Diagram file sharing in Earthstar

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#49]

**Comment by tripledoublev** [comment]
The use of Earthstar servers in the syncing process allows for quite a simple diagram. 
A user's replica <-> Server, ie. a user's concrete copy syncing with the always online server.
Servers can be multiple and offer redundancy but the premise remains the same: a user syncs with an always-online peer/server reachable via a public URL


All users have their concrete copy of the data, a **replica**. When they have access to the internet they connect with the server in order to share their replica's change and offer the latest content. This is a network design decision based on Earthstar's target audience, small groups that might not always be online. 

![Image](https://user-images.githubusercontent.com/631268/216985423-1214343f-ade7-4a61-ad10-1b4d447dda31.png)

**Comment by tripledoublev** [comment]
[Syncing and Earthstar servers](https://earthstar-project.org/docs/how-it-works#:~:text=syncing%20and%20earthstar%20servers)
