### ISSUE TITLE
Re-add control panel

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#70]

**Comment by writerly03** [comment]
Control panel button has disappeared. Adding as an issue so we don't forget about it over the dev break

**Comment by tripledoublev** [comment]
I added the Status Panel next to the Identity Details.

Status is only obtained after bytes are exchanged.
This means that at this time it will not appear if I access the app and Im already in sync with the server (ie. no documents are sent or received) Once I share an artifact, the panel would be made available.
This is because the panel needs such data in order to populate its elements. 

As I rework it, I will find a way to show minimal info until further details are accessible.

This Panel will eventually regroup information regarding status, share, identity and more.

**Comment by tripledoublev** [comment]
Identity and status are now visible.
Button to add share and server are now present in the sidebar
