### ISSUE TITLE
Create sidebar

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#74]
- [ ] input styling
- [ ] expose elements

**Comment by tripledoublev** [comment]
Side bar was created.

Next, I need to bring artifact interactions within the sidebar.

I will also need to integrate the shift between phases in order to:

- change background color based on currently visible phase
- change the display name of current phase to be shown within the panel
-  list the artifacts that are currently in that specific phase

To do so, I am thinking I will keep track of the scrolling/view and have a variable that will keep track on the current phase *in view*
